export default {
    root: 'assets/img',
    list: [
        '1.jpg',
        '2.jpg',
        '3.jfif',
        '4.jfif',
        '5.jfif',
        '6.jfif',
        '7.jfif',
        '8.jfif',
        '9.jfif',
        '10.jfif',
        '11.jpg',
        '12.jpeg',
        '13.jfif',
        '14.jfif',
        '15.jfif',
        '16.jfif',
        '17.jpg',
        '18.jfif',
        '19.jfif',
        '20.png',
        '21.png',
        '22.jfif',
        '23.jfif',
        '24.jfif',
        '25.jfif',
        '26.jpg',
        '27.jpg',
        '28.png',
        '29.jpg',
        '30.jfif',
        '31.jfif',
        '32.jfif',
        '33.jfif'
    ]
}